imports: 
  commons: commons.yml
  types: types.yml
  examples: examples.yml
  pagination: pagination.yml
  source: source.yml
  variables: variables.yml

types: 
  
  HttpServiceSchema: 
    extends: 
      - commons.WithDisplayName
      - commons.WithAudiences
    properties: 
      auth: boolean
      url: optional<string>
      base-path: optional<string>
      path-parameters: optional<map<string, string>>
      idempotent: optional<boolean>
      headers: optional<map<string, types.TypeReferenceSchema>>
      transport: optional<ServiceTransport> 
      source: optional<source.SourceSchema>
      endpoints: optional<map<string, HttpEndpointSchema>>

  ServiceTransport: 
    properties: 
      grpc: optional<GrpcTransport>        
  
  GrpcTransport: 
    properties: 
      service-name: 
        type: string
        docs: "The name of the gRPC service."
  
  HttpEndpointSchema:   
    extends: 
      - commons.WithDisplayName
      - commons.WithAudiences
    properties: 
      method: optional<HttpMethodSchema>
      base-path: string
      path: string
      url: optional<string>
      path-parameters: optional<map<string, HttpPathParameterSchema>>
      auth: optional<boolean>
      idempotent: optional<boolean>
      stream-condition: optional<string>
      request: optional<HttpRequest>
      response: optional<HttpResponseSchema>
      response-stream: optional<HttpResponseStreamSchema>
      errors: optional<ResponseErrorsSchema>
      examples: optional<list<examples.ExampleEndpointCallSchema>>
      pagination: optional<Pagination>
  
  HttpMethodSchema: 
    enum: 
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
  
  HttpRequest: 
    discriminated: false
    union: 
      - string
      - HttpRequestSchema

  HttpRequestSchema:
    extends: 
      - commons.WithName
      - commons.WithDocs
    properties: 
      content-type: optional<string>
      query-parameters: optional<map<string, HttpQueryParameterSchema>>
      headers: optional<map<string, HttpHeaderSchema>>
      body: optional<HttpRequestBodySchema>
  
  HttpHeaderSchema: 
    extends: 
      - types.TypeReferenceDetailed
    properties: 
      env: optional<string>
  
  HttpRequestBodySchema: 
    discriminated: false
    union: 
      - string
      - HttpReferencedRequestBodySchema
      - HttpInlineRequestBodySchema
  
  HttpReferencedRequestBodySchema: 
    extends: 
      - commons.WithDocs
    properties:
      type: string

  HttpInlineRequestBodySchema: 
    properties: 
      extends: optional<types.ObjectExtendsSchema>
      extra-properties: optional<boolean>
      properties: optional<HttpInlineRequestBodyProperty>

  HttpInlineRequestBodyProperty: 
    extends: 
      - types.TypeReferenceDetailed
    properties: 
      content-type: optional<string>
  
  HttpQueryParameterSchema: 
    discriminated: false
    union: 
      - string
      - QueryParameterTypeReferenceDetailed
  
  QueryParameterTypeReferenceDetailed: 
    extends: 
      - types.TypeReferenceDetailed
    properties: 
      allow-multiple: optional<boolean>
  
  HttpResponseSchema: 
    discriminated: false
    union: 
      - string
      - HttpResponseSchemaDetailed
  
  HttpResponseSchemaDetailed: 
    properties: 
      type: string
      property: optional<string>
      status-code: optional<integer>

  HttpResponseStreamSchema: 
    discriminated: false
    union: 
      - string
      - HttpResponseStreamSchemaDetailed
  
  HttpResponseStreamSchemaDetailed: 
    properties: 
      type: string
      format: optional<StreamFormat>
      terminator: optional<string>

  StreamFormat: 
    enum: 
      - sse
      - json
  
  HttpPathParameterSchema: 
    discriminated: false
    union: 
      - types.TypeReferenceSchema
      - variables.VariableReferenceSchema
  
  Pagination: 
    discriminated: false
    union: 
      - pagination.PaginationSchema
      - boolean
  
  ResponseErrorsSchema: 
    type: list<ResponseError>

  ResponseError: 
    discriminated: false
    union: 
      - string
      - ResponseErrorWithDocs
  
  ResponseErrorWithDocs: 
    extends: 
      - commons.WithDocs
    properties: 
      error: string
